# Generated by Django 3.2.7 on 2021-09-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='2006-10-25'),
            preserve_default=False,
        ),
    ]
