# Generated by Django 3.2.7 on 2021-09-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210919_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Estatura (en metros)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Nombre (s)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
