# Generated by Django 3.2.7 on 2021-09-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210918_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tienda')),
                ('type', models.CharField(choices=[('Abarrotes', 'Abarrotes'), ('Auttoservicio', 'Autoservicio')], default='Autoservice', max_length=15, verbose_name='Tipo de tienda')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
    ]
